Repository Medical-Information/medical-information-frontend, pull requests merged in 2023-07, with the labels that each got.

#7 #6 build(styles): upload sass and normalize, create structure of folder styles
  package-lock.json
  package.json
  src/App.tsx
  src/index.tsx
  src/styles/abstracts/functions.scss
  src/styles/abstracts/mixins.scss
  src/styles/abstracts/placeholders.scss
  src/styles/abstracts/variables/animations.scss
  src/styles/abstracts/variables/colors.scss
  src/styles/abstracts/variables/media-queries.scss
  src/styles/abstracts/variables/typography.scss
  src/styles/abstracts/variables/wrappers.scss
  src/styles/abstracts/variables/z-index.scss
  src/styles/globals.scss
  src/styles/index.scss
Labels: enhancement

#16 Feat/general styles
  .prettierrc.json
  .storybook/preview.ts
  src/App.tsx
  src/assets/fonts/fonts.scss
  src/assets/fonts/source/IBMPlexSans-Bold.ttf
  src/assets/fonts/source/IBMPlexSans-Bold.woff
  src/assets/fonts/source/IBMPlexSans-Bold.woff2
  src/assets/fonts/source/IBMPlexSans-Light.ttf
  src/assets/fonts/source/IBMPlexSans-Light.woff
  src/assets/fonts/source/IBMPlexSans-Light.woff2
  src/assets/fonts/source/IBMPlexSans-Regular.ttf
  src/assets/fonts/source/IBMPlexSans-Regular.woff
  src/assets/fonts/source/IBMPlexSans-Regular.woff2
  src/assets/fonts/source/IBMPlexSans-SemiBold.ttf
  src/assets/fonts/source/IBMPlexSans-SemiBold.woff
  src/assets/fonts/source/IBMPlexSans-SemiBold.woff2
  src/assets/styles/abstracts/functions.scss
  src/assets/styles/abstracts/mixins.scss
  src/assets/styles/abstracts/placeholders.scss
  src/assets/styles/abstracts/variables/animations.scss
  src/assets/styles/abstracts/variables/colors.scss
  src/assets/styles/abstracts/variables/fonts.scss
  src/assets/styles/abstracts/variables/media-queries.scss
  src/assets/styles/abstracts/variables/wrappers.scss
  src/assets/styles/abstracts/variables/z-index.scss
  src/assets/styles/globals.scss
  src/assets/styles/index.scss
  src/index.tsx
  src/reportWebVitals.ts
  src/setupTests.ts
  src/shared/button/Button.stories.ts
  src/shared/button/Button.tsx
  src/shared/button/button.css
  src/styles/abstracts/variables/typography.scss
  src/styles/abstracts/variables/wrappers.scss
  src/styles/abstracts/variables/z-index.scss
Labels: enhancement

#18 chore: change base url into tsconfig
  tsconfig.json
Labels: documentation

#20 feat(placeholders.scss): describe text styles
  src/assets/styles/abstracts/placeholders.scss
Labels: enhancement

#21 feat(logo): add component logo
  src/assets/images/Logo.svg
  src/shared/logo/index.tsx
  src/shared/logo/logo.stories.ts
Labels: enhancement

#23 feat(shared/buttons/button): create button with storybook
  package.json
  src/assets/icons/cancel.svg
  src/assets/styles/abstracts/variables/animations.scss
  src/shared/button/Button.stories.ts
  src/shared/button/Button.tsx
  src/shared/button/button.css
  src/shared/buttons/button/button.module.scss
  src/shared/buttons/button/button.stories.tsx
  src/shared/buttons/button/button.tsx
  src/shared/buttons/favorite-button/favorite-button.module.scss
  src/shared/buttons/favorite-button/favorite-button.stories.tsx
  src/shared/buttons/favorite-button/favorite-button.tsx
  src/shared/checkboxes/filter-checkbox/filter-checkbox.module.scss
  src/shared/checkboxes/filter-checkbox/filter-checkbox.stories.tsx
  src/shared/checkboxes/filter-checkbox/filter-checkbox.tsx
  src/shared/checkboxes/filter-tab/filter-tab.module.scss
  src/shared/checkboxes/filter-tab/filter-tab.stories.tsx
  src/shared/checkboxes/filter-tab/filter-tab.tsx
Labels: enhancement

#27 feat(shared/checkboxes/consent-checkbox): create consent checkbox wit…
  src/assets/icons/consent.svg
  src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
  src/shared/checkboxes/consent-checkbox/consent-checkbox.stories.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
Labels: enhancement

#29 feat(components/footer): create footer with storybook
  .storybook/main.ts
  package-lock.json
  package.json
  src/assets/documents/privacy-policy.pdf
  src/assets/documents/terms-of-use.pdf
  src/assets/styles/abstracts/variables/wrappers.scss
  src/components/footer/footer.module.scss
  src/components/footer/footer.stories.tsx
  src/components/footer/footer.tsx
  src/components/footer/test-icons/telegram.svg
  src/components/footer/test-icons/vk.svg
  src/components/footer/test-icons/youtube.svg
  src/index.tsx
  src/types.d.ts
  src/utils/data/footer/contacts.tsx
  src/utils/data/footer/links.tsx
  src/utils/routes.tsx
  tsconfig.json
Labels: enhancement

#42 Feat/card question doctor
  src/assets/styles/abstracts/placeholders.scss
  src/assets/styles/abstracts/variables/colors.scss
  src/assets/styles/abstracts/variables/fonts.scss
  src/components/cards/more-content/more-content.module.scss
  src/components/cards/more-content/more-content.stories.tsx
  src/components/cards/more-content/more-content.tsx
  src/components/cards/question-doctor/question-doctor.module.scss
  src/components/cards/question-doctor/question-doctor.stories.tsx
  src/components/cards/question-doctor/question-doctor.tsx
  src/shared/icons/utils.tsx
Labels: enhancement

#44 feat(button-with-icon): create button and describe with storybook
  src/shared/buttons/button-with-icon/button-with-icon.module.scss
  src/shared/buttons/button-with-icon/button-with-icon.stories.tsx
  src/shared/buttons/button-with-icon/button-with-icon.tsx
Labels: enhancement

#48 feat(components/articles): mark up gallery with articles
  src/components/articles/articles.module.scss
  src/components/articles/articles.tsx
  src/components/articles/test-data/test-data.tsx
  src/components/cards/article-preview/article-preview.stories.tsx
  src/components/cards/article-preview/article-preview.tsx
  src/components/cards/more-content/more-content.module.scss
Labels: enhancement

#54 Feat/section ask doctor
  src/components/ask-doctor/ask-doctor.module.scss
  src/components/ask-doctor/ask-doctor.tsx
  src/components/ask-doctor/test-data/test-data.tsx
  src/components/cards/question-doctor/question-doctor.module.scss
  src/components/footer/footer.module.scss
  src/pages/MainPage.tsx
  src/utils/functions/shuffle-data.tsx
Labels: enhancement

#55 feat(components/news): mark up section
  src/components/header/styles.module.scss
  src/components/news/news.module.scss
  src/components/news/news.tsx
  src/components/news/test-data/test-data.tsx
  src/pages/MainPage.tsx
Labels: enhancement

#62 Feat/section medicines
  src/assets/images/bg_bad.jpg
  src/assets/images/bg_lekarstva.jpg
  src/assets/styles/abstracts/placeholders.scss
  src/assets/styles/abstracts/variables/fonts.scss
  src/components/medicines/medicines.module.scss
  src/components/medicines/medicines.tsx
  src/pages/main-page/MainPage.tsx
  src/utils/data/medicines/links.tsx
Labels: enhancement

#63 feat(cards/article-preview): create card's type news
  src/components/cards/article-preview/article-preview.module.scss
  src/components/cards/article-preview/article-preview.stories.tsx
  src/components/cards/article-preview/article-preview.tsx
Labels: enhancement

#67 Feat/pages news
  src/App.tsx
  src/assets/styles/abstracts/variables/wrappers.scss
  src/components/cards/article-preview/article-preview.module.scss
  src/components/cards/article-preview/article-preview.stories.tsx
  src/components/cards/article-preview/article-preview.tsx
  src/pages/news-preview-page/news-preview-page.module.scss
  src/pages/news-preview-page/news-preview-page.tsx
  src/utils/routes.tsx
Labels: enhancement

#81 Feat/get server data
  src/components/articles/articles.tsx
  src/components/articles/test-data/test-data.tsx
  src/components/cards/article-preview/article-preview.module.scss
  src/components/cards/article-preview/article-preview.stories.tsx
  src/components/cards/article-preview/article-preview.tsx
  src/components/carousel/test-data/test-data.tsx
  src/components/news/news.module.scss
  src/services/app/store.tsx
  src/services/features/articles/api.tsx
  src/shared/checkboxes/filter-checkbox/filter-checkbox.stories.tsx
  src/shared/checkboxes/filter-checkbox/filter-checkbox.tsx
  src/shared/checkboxes/filter-tab/filter-tab.stories.tsx
  src/shared/checkboxes/filter-tab/filter-tab.tsx
  src/utils/api-routes.tsx
  src/utils/types/article.tsx
Labels: enhancement

#102 refactor(render-format-date-article): take into account difference of…
  src/utils/functions/render-format-date-article.tsx
Labels: refactor

#103 refactor(filter-tab.module.scss): add color effects for inner layout …
  src/shared/checkboxes/filter-tab/filter-tab.module.scss
Labels: refactor

#104 feat/popup/filters
  src/components/popup/filters/data/filtersData.ts
  src/components/popup/filters/filters.stories.tsx
  src/components/popup/filters/index.tsx
  src/components/popup/filters/styles.module.scss
Labels: enhancement

#101 refactor(input): change input
  package-lock.json
  package.json
  src/shared/icons/utils.tsx
  src/shared/input/input.module.scss
  src/shared/input/input.stories.tsx
  src/shared/input/input.tsx
Labels: enhancement

#106 Feat/pages entry
  src/App.tsx
  src/assets/styles/abstracts/variables/wrappers.scss
  src/components/entry/entry.module.scss
  src/components/entry/entry.tsx
  src/pages/articles-preview-page/articles-preview-page.tsx
  src/pages/error-page/index.tsx
  src/pages/main-page/MainPage.tsx
  src/pages/news-preview-page/news-preview-page.tsx
  src/pages/sign-in/sign-in.module.scss
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up/sign-up.module.scss
  src/pages/sign-up/sign-up.tsx
  src/shared/buttons/button/button.module.scss
  src/shared/checkboxes/consent-checkbox/consent-checkbox.stories.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
  src/shared/icons/utils.tsx
  src/shared/input/input.tsx
  src/utils/routes.tsx
Labels: enhancement

#129 Feat/entry business logic validation
  package-lock.json
  package.json
  src/assets/images/Logo.svg
  src/components/entry/entry.module.scss
  src/components/entry/entry.tsx
  src/pages/sign-in/sign-in.module.scss
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up/sign-up.module.scss
  src/pages/sign-up/sign-up.tsx
  src/services/app/hooks.tsx
  src/services/app/store.tsx
  src/services/features/user/api.tsx
  src/services/features/user/middlewares.tsx
  src/services/features/user/selectors.tsx
  src/services/features/user/slice.tsx
  src/services/features/user/types.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
  src/shared/checkboxes/consent-checkbox/consent-checkbox.stories.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
  src/shared/input/input.module.scss
  src/shared/input/input.tsx
  src/utils/api-routes.tsx
  src/utils/data/validation/validation-errors.tsx
  src/utils/data/validation/yup-schema.tsx
  src/utils/functions/filter-form-values.tsx
  src/utils/regex.tsx
Labels: enhancement
