Repository Medical-Information/medical-information-frontend, pull requests merged in 2023-08, with the labels that each got.

#130 Feat/entry business logic
  package-lock.json
  package.json
  src/App.tsx
  src/components/entry/entry.module.scss
  src/components/entry/entry.tsx
  src/pages/sign-in/sign-in.module.scss
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up/sign-up.module.scss
  src/pages/sign-up/sign-up.tsx
  src/services/app/hooks.tsx
  src/services/app/store.ts
  src/services/features/user/api.tsx
  src/services/features/user/middlewares.tsx
  src/services/features/user/selectors.tsx
  src/services/features/user/slice.tsx
  src/services/features/user/types.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
  src/shared/checkboxes/consent-checkbox/consent-checkbox.stories.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
  src/shared/input/input.module.scss
  src/shared/input/input.stories.tsx
  src/shared/input/input.tsx
  src/utils/api-routes.ts
  src/utils/data/validation/validation-errors.tsx
  src/utils/data/validation/yup-schema.tsx
  src/utils/functions/filter-form-values.tsx
  src/utils/regex.tsx
Labels: enhancement

#144 Pages/profile
  src/App.tsx
  src/components/sidebar/sidebar.module.scss
  src/components/sidebar/sidebar.tsx
  src/components/user-profile/user-profile.module.scss
  src/components/user-profile/user-profile.tsx
  src/pages/main-page/main-page.tsx
  src/pages/profile/profile-page.module.scss
  src/pages/profile/profile-page.tsx
  src/pages/sign-in/sign-in.tsx
  src/shared/input/input.module.scss
  src/utils/routes.ts
Labels: enhancement

#147 Feat/news article pages
  src/App.tsx
  src/components/articles-preview-small/index.tsx
  src/components/articles-preview-small/styles.module.scss
  src/components/articles/articles.tsx
  src/components/cards/article-preview/article-preview.module.scss
  src/components/cards/article-preview/article-preview.stories.tsx
  src/components/cards/article-preview/article-preview.tsx
  src/components/news-preview-small/index.tsx
  src/components/news/news.tsx
  src/components/paper/index.tsx
  src/components/paper/styles.module.scss
  src/pages/article/index.tsx
  src/pages/article/styles.module.scss
  src/pages/articles-preview-page/articles-preview-page.tsx
  src/pages/news-preview-page/news-preview-page.tsx
  src/pages/news/index.tsx
  src/pages/news/styles.module.scss
  src/services/app/store.ts
  src/services/features/information-material/api.ts
  src/utils/previewSmall/index.ts
Labels: enhancement

#151 Feat/forgot password
  src/App.tsx
  src/components/entry/entry.tsx
  src/pages/reset-password-confirmation/reset-password-confirmation.module.scss
  src/pages/reset-password-confirmation/reset-password-confirmation.tsx
  src/pages/reset-password/reset-password.module.scss
  src/pages/reset-password/reset-password.tsx
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up/sign-up.tsx
  src/shared/icons/icons.mdx
  src/shared/icons/index.tsx
  src/shared/icons/status-icon.tsx
  src/shared/icons/utils.tsx
  src/shared/mail-with-icon/mail-with-icon.module.scss
  src/shared/mail-with-icon/mail-with-icon.stories.tsx
  src/shared/mail-with-icon/mail-with-icon.tsx
  src/utils/api-routes.ts
  src/utils/api.ts
  src/utils/regex.ts
  src/utils/routes.ts
Labels: enhancement

#157 Feat/email confirmation
  src/App.tsx
  src/components/entry/entry.tsx
  src/pages/articles-preview-page/articles-preview-page.tsx
  src/pages/reset-password-confirmation/reset-password-confirmation.module.scss
  src/pages/reset-password/reset-password.tsx
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up-activation/sign-up-activation.module.scss
  src/pages/sign-up-activation/sign-up-activation.tsx
  src/pages/sign-up/sign-up.module.scss
  src/pages/sign-up/sign-up.tsx
  src/services/features/user/types.tsx
  src/shared/buttons/button/button.module.scss
  src/shared/buttons/button/button.stories.tsx
  src/shared/buttons/button/button.tsx
  src/shared/icons/status-icon.tsx
  src/shared/icons/utils.tsx
  src/shared/input/input.tsx
  src/shared/mail-with-icon/mail-with-icon.stories.tsx
  src/shared/mail-with-icon/mail-with-icon.tsx
  src/shared/preloaders/circle-with-dots/circle-with-dots.module.scss
  src/shared/preloaders/circle-with-dots/circle-with-dots.tsx
  src/utils/api-routes.ts
  src/utils/api.ts
  src/utils/data/footer/links.ts
  src/utils/data/medicines/links.ts
  src/utils/data/validation/validation-errors.ts
  src/utils/data/validation/yup-schema.ts
  src/utils/functions/filter-form-values.ts
  src/utils/functions/find-reading-time-article.ts
  src/utils/functions/render-format-date-article.ts
  src/utils/functions/shuffle-data.ts
  src/utils/routes.ts
Labels: enhancement

#170 Feat/create article
  .eslintrc.json
  src/App.tsx
  src/assets/styles/abstracts/variables/wrappers.scss
  src/components/sidebar/sidebar.module.scss
  src/components/sidebar/sidebar.tsx
  src/pages/authors/authors.module.scss
  src/pages/authors/authors.tsx
  src/pages/creating-an-article/components/response.module.scss
  src/pages/creating-an-article/components/response.tsx
  src/pages/creating-an-article/creating-an-article.module.scss
  src/pages/creating-an-article/creating-an-article.tsx
  src/pages/profile/profile-page.module.scss
  src/pages/profile/profile-page.tsx
  src/pages/reset-password/reset-password.tsx
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up/sign-up.tsx
  src/shared/buttons/button-with-icon-two/button-with-icon-two.tsx
  src/shared/file-input/file-input.module.scss
  src/shared/file-input/file-input.stories.tsx
  src/shared/file-input/file-input.tsx
  src/shared/icons/icons.mdx
  src/shared/icons/index.tsx
  src/shared/icons/paper-clip-icon.tsx
  src/shared/icons/utils.tsx
  src/shared/input/input.module.scss
  src/shared/input/input.stories.tsx
  src/shared/input/input.tsx
  src/shared/text-area/lib.ts
  src/shared/text-area/text-area.module.scss
  src/shared/text-area/text-area.stories.tsx
  src/shared/text-area/text-area.tsx
  src/utils/api.ts
  src/utils/constants.ts
  src/utils/data/validation/validation-errors.ts
  src/utils/data/validation/yup-schema.ts
  src/utils/regex.ts
  src/utils/routes.ts
  src/utils/types/article.tsx
Labels: enhancement

#178 refactor(pages/about-us): remake gallery with team due to new design …
  src/App.tsx
  src/assets/images/CreatorFemale.png
  src/assets/images/CreatorMale.png
  src/components/breadcrumbs/index.tsx
  src/pages/about-page/about-page.module.scss
  src/pages/about-page/about-page.tsx
  src/pages/about-page/test-data/index.tsx
  src/pages/about-us/about-us.module.scss
  src/pages/about-us/about-us.tsx
  src/shared/icons/icons.mdx
  src/shared/icons/index.tsx
  src/shared/icons/social-behance-icon.tsx
  src/shared/icons/social-github-icon.tsx
  src/shared/icons/social-telegram-icon.tsx
  src/utils/data/about-us/our-team.ts
  src/utils/routes.ts
Labels: enhancement

#181 Feat/profile
  src/assets/styles/abstracts/variables/wrappers.scss
  src/components/header/index.tsx
  src/components/header/styles.module.scss
  src/components/sidebar/components/avatar-modal/avatar-modal.module.scss
  src/components/sidebar/components/avatar-modal/avatar-modal.tsx
  src/components/sidebar/components/avatar/avatar.module.scss
  src/components/sidebar/components/avatar/avatar.tsx
  src/components/sidebar/sidebar.module.scss
  src/components/sidebar/sidebar.tsx
  src/components/user-header-icon/index.tsx
  src/components/user-header-icon/styles.module.scss
  src/components/user-profile/components/password-changing/password-changing.module.scss
  src/components/user-profile/components/password-changing/password-changing.tsx
  src/components/user-profile/components/personal-data/personal-data.module.scss
  src/components/user-profile/components/personal-data/personal-data.tsx
  src/components/user-profile/user-profile.module.scss
  src/components/user-profile/user-profile.tsx
  src/pages/creating-an-article/creating-an-article.module.scss
  src/pages/creating-an-article/creating-an-article.tsx
  src/pages/favorites/favorites.tsx
  src/pages/main-page/main-page.tsx
  src/pages/profile/profile-page.module.scss
  src/pages/profile/profile-page.tsx
  src/pages/sign-up/sign-up.tsx
  src/services/features/user/api.tsx
  src/services/features/user/middlewares.tsx
  src/services/features/user/slice.tsx
  src/services/features/user/types.tsx
  src/shared/buttons/button-with-icon/button-with-icon.module.scss
  src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
  src/shared/icons/edit-with-border-icon.tsx
  src/shared/icons/icons.mdx
  src/shared/icons/index.tsx
  src/shared/icons/logout-two-icon.tsx
  src/shared/icons/utils.tsx
  src/shared/input/input.tsx
  src/shared/overlaying-popup/overlaying-popup.module.scss
  src/utils/api-routes.ts
  src/utils/api.ts
  src/utils/constants.ts
  src/utils/data/validation/validation-errors.ts
  src/utils/data/validation/yup-schema.ts
Labels: enhancement

#183 feat(hocs/withprotectedroute): protect routes
  src/App.tsx
  src/hocs/withProtectedRoute.tsx
  src/pages/reset-password-confirmation/reset-password-confirmation.tsx
  src/pages/reset-password/reset-password.tsx
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up-activation/sign-up-activation.tsx
  src/pages/sign-up/sign-up.tsx
  src/services/features/user/selectors.tsx
  src/services/features/user/slice.tsx
Labels: enhancement

#188 Feat/head
  public/android-chrome-192x192.png
  public/android-chrome-512x512.png
  public/apple-touch-icon.png
  public/favicon-16x16.png
  public/favicon-32x32.png
  public/favicon.ico
  public/index.html
  public/site.webmanifest
  src/components/cards/article-preview/article-preview.module.scss
  src/components/cards/article-preview/article-preview.tsx
Labels: enhancement

#190 fix(header & footer): change styles according to Pixel Perfect
  src/components/footer/footer.module.scss
  src/components/header/index.tsx
  src/components/header/menu/styles.module.scss
  src/components/header/search/styles.module.scss
  src/components/header/styles.module.scss
Labels: refactor

#217 Forms validation
  src/components/entry/entry.module.scss
  src/components/entry/entry.tsx
  src/components/header/index.tsx
  src/components/sidebar/sidebar.tsx
  src/components/user-profile-icon/styles.module.scss
  src/components/user-profile/components/password-changing/password-changing.tsx
  src/components/user-profile/user-profile.module.scss
  src/components/user-profile/user-profile.tsx
  src/pages/reset-password-confirmation/reset-password-confirmation.tsx
  src/pages/reset-password/reset-password.tsx
  src/pages/sign-in/sign-in.tsx
  src/pages/sign-up/sign-up.tsx
  src/services/app/hooks.ts
  src/shared/checkboxes/consent-checkbox/consent-checkbox.module.scss
  src/shared/checkboxes/consent-checkbox/consent-checkbox.stories.tsx
  src/shared/checkboxes/consent-checkbox/consent-checkbox.tsx
  src/shared/input/input.stories.tsx
  src/shared/input/input.tsx
  src/utils/api.ts
  src/utils/data/validation/validation-errors.ts
  src/utils/data/validation/yup-schema.ts
  src/utils/functions/filter-form-values.ts
  src/utils/regex.ts
Labels: bug, enhancement
